#! /bin/bash

. ./scripts/common.sh

# Find Python 3.x details
find_python python3 PY3_EXECUTABLE PY3_VER PY3_INCLUDE_DIR PY3_LIBRARY
echo "PY3_EXECUTABLE=${PY3_EXECUTABLE}"
echo "PY3_VER=${PY3_VER}"
echo "PY3_INCLUDE_DIR=${PY3_INCLUDE_DIR}"
echo "PY3_LIBRARY=${PY3_LIBRARY}"
CMAKE_PY3_OPTS="-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DBUILD_PYTHON="ON" -DPYTHON_EXECUTABLE=${PY3_EXECUTABLE} -DPYTHON_INCLUDE_DIR=${PY3_INCLUDE_DIR} -DPYTHON_LIBRARY=${PY3_LIBRARY}"

# Remove old Python bindings and build dir
#rm -rf "${PROTON_BINDINGS_INSTALL_DIR}/python"
#rm -rf "${PROTON_BINDINGS_INSTALL_DIR}/python3"
#rm -rf "${PROTON_BUILD_DIR}"

mkdir -p ${PROTON_BUILD_DIR}
cd ${PROTON_BUILD_DIR}

# Build Python 3.x
echo "CMAKE_PY3_OPTS=${CMAKE_PY3_OPTS}"
cmake ${CMAKE_PY3_OPTS} ..
make
